DungeonData = {
    ["Classic"] = {
        Dungeons = {
            "Blackfathom Deeps",
            "Blackrock Depths",
            "Deadmines",
            "Dire Maul",
            "Gnomeregan",
            "Maraudon",
            "Ragefire Chasm",
            "Razorfen Downs",
            "Razorfen Kraul",
            "Scarlet Monastery",
            "Scholomance",
            "Shadowfang Keep",
            "Stratholme",
            "Sunken Temple",
            "Uldaman",
            "Wailing Caverns",
            "Zul'Farrak",
        },
        Raids = {
            "Molten Core",
            "Blackwing Lair",
            "Ruins of Ahn'Qiraj",
            "Temple of Ahn'Qiraj",
            "Naxxramas",
        },
    },

    ["The Burning Crusade"] = {
        Dungeons = {
            "Hellfire Ramparts",
            "The Blood Furnace",
            "The Shattered Halls",
            "Mana-Tombs",
            "Auchenai Crypts",
            "Sethekk Halls",
            "Shadow Labyrinth",
            "The Slave Pens",
            "The Underbog",
            "The Steamvault",
            "Old Hillsbrad Foothills",
            "The Black Morass",
            "Magisters' Terrace",
        },
        Raids = {
            "Karazhan",
            "Gruul's Lair",
            "Magtheridon's Lair",
            "Serpentshrine Cavern",
            "Tempest Keep",
            "Battle for Mount Hyjal",
            "Black Temple",
            "Sunwell Plateau",
        },
    },

    ["Wrath of the Lich King"] = {
        Dungeons = {
            "Utgarde Keep",
            "Utgarde Pinnacle",
            "The Nexus",
            "The Oculus",
            "Azjol-Nerub",
            "Ahn'kahet: The Old Kingdom",
            "Drak'Tharon Keep",
            "Gundrak",
            "Halls of Stone",
            "Halls of Lightning",
            "The Violet Hold",
            "The Culling of Stratholme",
            "Trial of the Champion",
            "Forge of Souls",
            "Pit of Saron",
            "Halls of Reflection",
        },
        Raids = {
            "Naxxramas",
            "The Obsidian Sanctum",
            "The Eye of Eternity",
            "Vault of Archavon",
            "Ulduar",
            "Trial of the Crusader",
            "Onyxia's Lair",
            "Icecrown Citadel",
            "The Ruby Sanctum",
        },
    },

    ["Cataclysm"] = {
        Dungeons = {
            "Blackrock Caverns",
            "Throne of the Tides",
            "The Stonecore",
            "The Vortex Pinnacle",
            "Lost City of the Tol'vir",
            "Halls of Origination",
            "Grim Batol",
            "Deadmines (Heroic)",
            "Shadowfang Keep (Heroic)",
            "End Time",
            "Well of Eternity",
            "Hour of Twilight",
            "Zul'Aman",
            "Zul'Gurub",
        },
        Raids = {
            "Baradin Hold",
            "Blackwing Descent",
            "The Bastion of Twilight",
            "Throne of the Four Winds",
            "Firelands",
            "Dragon Soul",
        },
    },

    ["Mists of Pandaria"] = {
        Dungeons = {
            "Temple of the Jade Serpent",
            "Stormstout Brewery",
            "Shado-Pan Monastery",
            "Gate of the Setting Sun",
            "Scarlet Halls",
            "Scarlet Monastery",
            "Siege of Niuzao Temple",
            "Mogu'shan Palace",
        },
        Raids = {
            "Mogu'shan Vaults",
            "Heart of Fear",
            "Terrace of Endless Spring",
            "Throne of Thunder",
            "Siege of Orgrimmar",
        },
    },

    ["Warlords of Draenor"] = {
        Dungeons = {
            "Bloodmaul Slag Mines",
            "Iron Docks",
            "Auchindoun",
            "Skyreach",
            "Shadowmoon Burial Grounds",
            "Grimrail Depot",
            "The Everbloom",
            "Upper Blackrock Spire",
        },
        Raids = {
            "Highmaul",
            "Blackrock Foundry",
            "Hellfire Citadel",
        },
    },

    ["Legion"] = {
        Dungeons = {
            "Eye of Azshara",
            "Darkheart Thicket",
            "Neltharion's Lair",
            "Halls of Valor",
            "Maw of Souls",
            "Vault of the Wardens",
            "Black Rook Hold",
            "Court of Stars",
            "The Arcway",
            "Cathedral of Eternal Night",
            "Seat of the Triumvirate",
        },
        Raids = {
            "The Emerald Nightmare",
            "Trial of Valor",
            "The Nighthold",
            "Tomb of Sargeras",
            "Antorus, the Burning Throne",
        },
    },

    ["Battle for Azeroth"] = {
        Dungeons = {
            "Atal'Dazar",
            "Freehold",
            "Kings' Rest",
            "Shrine of the Storm",
            "Siege of Boralus",
            "Temple of Sethraliss",
            "The Motherlode",
            "The Underrot",
            "Tol Dagor",
            "Waycrest Manor",
            "Operation: Mechagon",
        },
        Raids = {
            "Uldir",
            "Battle of Dazar'alor",
            "Crucible of Storms",
            "The Eternal Palace",
            "Ny'alotha, the Waking City",
        },
    },

    ["Shadowlands"] = {
        Dungeons = {
            "The Necrotic Wake",
            "Plaguefall",
            "Mists of Tirna Scithe",
            "Halls of Atonement",
            "Theater of Pain",
            "De Other Side",
            "Spires of Ascension",
            "Sanguine Depths",
            "Tazavesh, the Veiled Market",
        },
        Raids = {
            "Castle Nathria",
            "Sanctum of Domination",
            "Sepulcher of the First Ones",
        },
    },

    ["Dragonflight"] = {
        Dungeons = {
            "Algeth'ar Academy",
            "Brackenhide Hollow",
            "Halls of Infusion",
            "Neltharus",
            "Ruby Life Pools",
            "The Azure Vault",
            "The Nokhud Offensive",
            "Uldaman: Legacy of Tyr",
            "Dawn of the Infinite",
        },
        Raids = {
            "Vault of the Incarnates",
            "Aberrus, the Shadowed Crucible",
            "Amirdrassil, the Dream's Hope",
        },
    },
}

return WoWExpansions
